#!/bin/bash
#
# terminal command to play movie. 
# input: movie file or episode number

re='^[0-9]+$'
if test "$#" -ne 1; then
	# play whatever movie is in the folder
	movie_name=$(ls . | grep "avi\|mp4\|mkv\|mpeg" )
	echo "Playing the following movie:"
	echo $movie_name
elif ! [[ $1 =~ $re ]] ; then
	# script input is not episode number
	movie_name=$1	
else 
	# script input is an episode number
	if [ "$1" -lt 10 ] ; then 
		re="*[xeXE]0$1*"
	else
		re="*[xeXE]$1*"
	fi
	ls $re
	movie_name=$(ls $re | grep -v '\bsrt$')
fi

no_ext="${movie_name%.*}"
echo $no_ext
subtitle=$(ls * | grep "$no_ext" | grep -m 1 srt)
if [ -z $subtitle ] ; then
	echo "Playing movie: " $movie_name " with no subtitle"
	mplayer "$movie_name"
else
	echo "Playing movie: " $movie_name " with subtitle: " $subtitle
	mplayer "$movie_name" -sub "$subtitle"
fi
